export const beneficiaryTypes = {
    ADD_BENEFICIARY:"ADD_BENEFICIARY",
    UPDATE_BENEFICIARY:"UPDATE_BENEFICIARY",
    GET_BENEFICIARIES:"GET_BENEFICIARIES",
    DELETE_BENEFICIARY:"DELETE_BENEFICIARY"

}