export const HouseProjectsTypes = {
    GET_HOUSEPROJECTS: "GET_HOUSEPROJECTS",
    UPDATE_HOUSEPROJECT: "UPDATE_HOUSEPROJECT",
    ADD_HOUSEPROJECT: "ADD_HOUSEPROJECT",
    DELETE_HOUSEPROJECT: "DELETE_HOUSEPROJECT",
  };
  